#!/usr/bin/env bash

# checking for command line arguments
if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# assigning paramentals to a variables

path_to_file=$1
ip=$2
username=$8
path_to_shh_key=$4

# disabling strict host key checking

scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

# checking for successful transfered files
if [ $? -eq 0 ]
then
	echo "file succesfully transfered"
else
	echo "file transfered failed"
fi
